import type { FeatureFlags } from '../shared/types/tenant';

/**
 * Plan-based feature configurations
 */
export const PLAN_FEATURES = {
  basic: {
    multiCurrency: false,
    multiLanguage: false,
    inventory: true,
    analytics: false,
    reporting: false,
    wishlist: false,
    reviews: true,
    ratings: true,
    compareProducts: false,
    recentlyViewed: true,
    loyaltyProgram: false,
    pointsSystem: false,
    referralProgram: false,
    coupons: true,
    flashDeals: false,
    bundleDeals: false,
    emailMarketing: false,
    smsMarketing: false,
    pushNotifications: false,
    socialMediaIntegration: true,
    blogModule: false,
    subscriptions: false,
    preOrders: false,
    backorders: false,
    productVariants: true,
    productBundles: false,
    giftCards: false,
    seoTools: true,
    sitemap: true,
    structuredData: false,
    pageSpeed: true,
    imageOptimization: true,
    api: false,
    webhooks: false,
    thirdPartyIntegrations: false,
    paymentGateways: ['stripe'],
    shippingProviders: ['standard'],
    marketplaceIntegrations: [],
    customDomain: false,
    whiteLabel: false,
    customCheckout: false,
    customEmails: false,
    liveChat: false,
    helpDesk: true,
    knowledgeBase: false,
    communityForum: false,
    twoFactorAuth: false,
    sslCertificate: true,
    gdprCompliance: true,
    dataBackup: false,
    auditLogs: false,
  } as FeatureFlags,
  
  premium: {
    multiCurrency: true,
    multiLanguage: true,
    inventory: true,
    analytics: true,
    reporting: true,
    wishlist: true,
    reviews: true,
    ratings: true,
    compareProducts: true,
    recentlyViewed: true,
    loyaltyProgram: true,
    pointsSystem: true,
    referralProgram: true,
    coupons: true,
    flashDeals: true,
    bundleDeals: true,
    emailMarketing: true,
    smsMarketing: true,
    pushNotifications: true,
    socialMediaIntegration: true,
    blogModule: true,
    subscriptions: true,
    preOrders: true,
    backorders: true,
    productVariants: true,
    productBundles: true,
    giftCards: true,
    seoTools: true,
    sitemap: true,
    structuredData: true,
    pageSpeed: true,
    imageOptimization: true,
    api: false,
    webhooks: true,
    thirdPartyIntegrations: true,
    paymentGateways: ['stripe', 'paypal', 'square'],
    shippingProviders: ['fedex', 'ups', 'dhl', 'standard'],
    marketplaceIntegrations: ['shopify', 'woocommerce'],
    customDomain: false,
    whiteLabel: false,
    customCheckout: true,
    customEmails: true,
    liveChat: true,
    helpDesk: true,
    knowledgeBase: true,
    communityForum: false,
    twoFactorAuth: true,
    sslCertificate: true,
    gdprCompliance: true,
    dataBackup: true,
    auditLogs: false,
  } as FeatureFlags,
  
  enterprise: {
    multiCurrency: true,
    multiLanguage: true,
    inventory: true,
    analytics: true,
    reporting: true,
    wishlist: true,
    reviews: true,
    ratings: true,
    compareProducts: true,
    recentlyViewed: true,
    loyaltyProgram: true,
    pointsSystem: true,
    referralProgram: true,
    coupons: true,
    flashDeals: true,
    bundleDeals: true,
    emailMarketing: true,
    smsMarketing: true,
    pushNotifications: true,
    socialMediaIntegration: true,
    blogModule: true,
    subscriptions: true,
    preOrders: true,
    backorders: true,
    productVariants: true,
    productBundles: true,
    giftCards: true,
    seoTools: true,
    sitemap: true,
    structuredData: true,
    pageSpeed: true,
    imageOptimization: true,
    api: true,
    webhooks: true,
    thirdPartyIntegrations: true,
    paymentGateways: ['stripe', 'paypal', 'square', 'adyen', 'custom'],
    shippingProviders: ['fedex', 'ups', 'dhl', 'usps', 'custom'],
    marketplaceIntegrations: ['amazon', 'ebay', 'shopify', 'magento', 'woocommerce'],
    customDomain: true,
    whiteLabel: true,
    customCheckout: true,
    customEmails: true,
    liveChat: true,
    helpDesk: true,
    knowledgeBase: true,
    communityForum: true,
    twoFactorAuth: true,
    sslCertificate: true,
    gdprCompliance: true,
    dataBackup: true,
    auditLogs: true,
  } as FeatureFlags,
} as const;

/**
 * Get features for a specific plan
 */
export const getFeaturesForPlan = (planType: 'basic' | 'premium' | 'enterprise'): FeatureFlags => {
  return PLAN_FEATURES[planType];
};

/**
 * Check if a feature is available for a plan
 */
export const isFeatureAvailableForPlan = (
  feature: keyof FeatureFlags, 
  planType: 'basic' | 'premium' | 'enterprise'
): boolean => {
  const planFeatures = PLAN_FEATURES[planType];
  return planFeatures[feature] === true;
};